import Image from "next/image";
import React from "react";

export default function Intervals() {
  return (
    <div className="flex flex-col w-full justify-center items-center">
      <h1>Intervals</h1>
      <Image
        className="theory-image"
        src={"/Theory/intervals1.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals2.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals3.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals4.png"}
        width={360}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals5.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals6.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals7.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals8.png"}
        width={360}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals9.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals10.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals11.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals12.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals13.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals14.png"}
        width={700}
        height={500}
        alt="intervals"
      />
      <Image
        className="theory-image"
        src={"/Theory/intervals15.png"}
        width={700}
        height={500}
        alt="intervals"
      />
    </div>
  );
}
